const data = [
  {
    name: "Anonymous",
    race: "white",
    birthDate: "2020",
    birthAge: "41",
    city: "Johannesburg",
    country: "South Africa",
    countryLivesIn: "South Africa",
    birthKind: "Vaginal",
    noOfChildren: "One",
    noOfChild: "First",
    portrait: "../images/anon-001-portrait.png",
    birthStory: "My daughter’s birth was a surprise, but a beautiful one. I was supposed to have a caesarean but she arrived early so I gave birth naturally, relying completely on the inherent wisdom of the female body. I breathed through it, drew on inner strength and it was truly a magical experience. I felt I had to take charge of the situation as the doctor was in a state, it was the midst of Covid, and my husband was fearful of natural birth. Because I hadn’t expected a natural childbirth I didn’t expect any sensations nor any consequences of the birth. In retrospect I am glad for this, however, I realise that knowledge is power with child birth and ensure the safety and health of mother and child. The first 40 days were tricky - my husband was supportive but not as I had imagined. I also still had to work. It was all a bit surreal, looking back!",
    sentences: [
      "My daughter’s birth was a surprise, but a beautiful one.",
      "I was supposed to have a caesarean but she arrived early so I gave birth naturally, relying completely on the inherent wisdom of the female body.",
      "I breathed through it, drew on inner strength and it was truly a magical experience.",
      "I felt I had to take charge of the situation as the doctor was in a state, it was the midst of Covid, and my husband was fearful of natural birth.",
      "Because I hadn’t expected a natural childbirth I didn’t expect any sensations nor any consequences of the birth. In retrospect I am glad for this, however, I realise that knowledge is power with child birth and ensure the safety and health of mother and child.",
      "The first 40 days were tricky - my husband was supportive but not as I had imagined. I also still had to work. It was all a bit surreal, looking back!",
    ],
  },

  {
    name: "Magdalena",
    race: "white",
    birthDate: "2014",
    birthAge: "36",
    city: "Cairo",
    country: "Egypt",
    countryLivesIn: "Germany",
    birthKind: "Caeserian",
    noOfChildren: "One",
    noOfChild: "First",
    portrait: "../images/magdalena-portrait.png",
    birthStory:
      "I don't want to share it. It was too horrible, and both the child and I are lucky to have survived. It was a disastrous emergency delivery in the 7th month of pregnancy in the hospital. My partner was present. They tried vaginal, which did not work due to the effects of radiation treatment [I] had received two years earlier, then switched to caesarian, but were not equipped with the right tools. It was a disaster, which almost cost both of our lives. It was kind of a medical miracle, but I wished to have a child. Horrible and in lots of pain. I witnessed everything even though they pumped me up with anaestetics. Due to the complication in giving birth to my first child, I cannot conceive more children. I got infected during the caesarian with 15 multiresistant bacteria, which could have killed me.",
    sentences: [
      "I don't want to share it. It was too horrible, and both the child and I are lucky to have survived.",
      "It was a disastrous emergency delivery in the 7th month of pregnancy in the hospital.",
      "My partner was present.",
      "They tried vaginal, which did not work due to the effects of radiation treatment [I] had received two years earlier, then switched to caesarian, but were not equipped with the right tools. It was a disaster, which almost cost both of our lives.",
      "It was kind of a medical miracle, but I wished to have a child.",
      "Due to the complication in giving birth to my first child, I cannot conceive more children.",
      "Horrible and in lots of pain. I witnessed everything even though they pumped me up with anaestetics", 
      "I got infected during the caesarian with 15 multiresistant bacteria, which could have killed me.",
    ],
  },

  {
    name: "Dee",
    race: "coloured",
    birthDate: "2023",
    birthAge: "38",
    city: "Johannesburg",
    country: "South Africa",
    countryLivesIn: "South Africa",
    birthKind: "Caeserian",
    noOfChildren: "Three",
    noOfChild: "Third",
    portrait: "../images/dee-portrait.png",
    birthStory:
      "Leaving the house was a very dramatic affair. I'd had two physical examinations - Karen checked once, after my water had broken in the passage - a big, gushing whoosh of release. I laughed, in my hot pink workout top and blue sarong around my hips. After my waters broke I abandoned the kikoy. I remember how in each pregnancy there's a moment that you forget your body for being a living thing that can be made pretty or fresher or lovelier or anything at all beyond a labouring body. My waters had never broken before - in the first labour, my midwife broke it and because I was already a few hours into labour (and laying down if I remember correctly), I didn't feel much. With the second one, she came with the waters! With this one, I wasn't expecting the waters at all... and then, the first indication that she would decide the pace and style of this labouring journey came this way... a big gush and release of water. There was some green in the waters and this led to my midwife wanting to check progress.Will and I drove to the birthing unit mostly in silence. Me on hands and feet on the back seat. Will in front, knuckles clenched and jaw tightening more than usual. It was impossible to even say a nice thing to each other although in that moment, I felt the silent affections between us... him wanting to say more, me still willing the baby to turn. I think back to the children at home - they looked so scared and confused. I remember thinking of novels I'd read before about mums being brave for their children; how being brave for the children required super human effort but was also, almost effortless, because immediately she knew it was required to protect them. They had been so excited before we left, singing and dancing 'The baby is coming today!' Yes, the baby is coming today, just not as planned.11am arrival - Karen walks down the short corridor of the birthing facility with determination.A little before 12 the baby is taken from my open body. She's shown to me. She moves across the room without me. Will, as many fathers in this situation feels torn. He goes with her, after I say not to worry about me. I lay there then, my body has expelled nothing, only dignity. Like in death, I imagine, one lay there, hoping for the best, aware that one exists now between a realm of here and there. With a vaginal delivery, I remember so distinctly the feeling of expelling the human. The separation of their body from the home that is (becomes 'was') my body is so distinct and real. The replacement of the person who was homed there for 9 months with a plethora or hormones is a vivid experience. It is alive and active. With the caesarian there was nothing like that. I remember thinking to myself how numb I felt, how absent, how desperate for the hormones - like I imagine one craves a drug. The irony was that I was on lots of drugs. In fact more than I'd ever been perhaps... but I hated every single clear liquid bag chugging into my veins. Into my veins, into the blood, into the milk, into her. I hated the drugs, I hated my body, I felt an indescribable sense of loss. Why!!? I'd seen and heard this many times before - the labour ended in an emergency caesar. Thankfully the baby and mum are safe. All that matters is that they are safe and here and alive. How much of this could i have changed, I still wonder now, to this very moment as I write these words.",
    sentences: [
      "Leaving the house was a very dramatic affair.",
      "I'd had two physical examinations - Karen checked once, after my water had broken in the passage - a big, gushing whoosh of release.",
      "I laughed, in my hot pink workout top and blue sarong around my hips. After my waters broke I abandoned the kikoy.",
      "I remember how in each pregnancy there's a moment that you forget your body for being a living thing that can be made pretty or fresher or lovelier or anything at all beyond a labouring body.",
      "My waters had never broken before - in the first labour, my midwife broke it and because I was already a few hours into labour (and laying down if I remember correctly), I didn't feel much.",
      "With the second one, she came with the waters! With this one, I wasn't expecting the waters at all... and then, the first indication that she would decide the pace and style of this labouring journey came this way... a big gush and release of water.",
      "There was some green in the waters and this led to my midwife wanting to check progress.",
      "Will and I drove to the birthing unit mostly in silence.",
      "Me on hands and feet on the back seat. Will in front, knuckles clenched and jaw tightening more than usual.",
      "It was impossible to even say a nice thing to each other although in that moment, I felt the silent affections between us... him wanting to say more, me still willing the baby to turn.",
      "I think back to the children at home - they looked so scared and confused.",
      "I remember thinking of novels I'd read before about mums being brave for their children; how being brave for the children required super human effort but was also, almost effortless, because immediately she knew it was required to protect them.",
      "They had been so excited before we left, singing and dancing 'The baby is coming today!' Yes, the baby is coming today, just not as planned. ",
      "11am arrival - Karen walks down the short corridor of the birthing facility with determination.",
      "A little before 12 the baby is taken from my open body. She's shown to me. She moves across the room without me.",
      "Will, as many fathers in this situation feels torn. He goes with her, after I say not to worry about me.",
      "I lay there then, my body has expelled nothing, only dignity.",
      "Like in death, I imagine, one lay there, hoping for the best, aware that one exists now between a realm of here and there.",
      "With a vaginal delivery, I remember so distinctly the feeling of expelling the human.",
      "The separation of their body from the home that is (becomes 'was') my body is so distinct and real.",
      "The replacement of the person who was homed there for 9 months with a plethora or hormones is a vivid experience. It is alive and active.",
      "With the caesarian there was nothing like that. I remember thinking to myself how numb I felt, how absent, how desperate for the hormones - like I imagine one craves a drug.",
      "The irony was that I was on lots of drugs. In fact more than I'd ever been perhaps... but I hated every single clear liquid bag chugging into my veins.",
      "Into my veins, into the blood, into the milk, into her. I hated the drugs, I hated my body, I felt an indescribable sense of loss. Why!!? I'd seen and heard this many times before - the labour ended in an emergency caesar.",
      "Thankfully the baby and mum are safe. All that matters is that they are safe and here and alive.",
      "How much of this could i have changed, I still wonder now, to this very moment as I write these words.",
    ],
  },

  {
    name: "Amanda",
    race: "white",
    birthDate: "2021",
    birthAge: "38",
    city: "Johannesburg",
    country: "South Africa",
    countryLivesIn: "South Africa",
    birthKind: "Caeserian",
    noOfChildren: "One",
    noOfChild: "First",
    portrait: "../images/amanda-portrait.png",
    birthStory:
      "I had to book an elective c-section because baby was breech. I tried to turn her but nothing worked. When I went in on the day of the c-section the midwife checked the heartbeat and said I was in labour so it was actually perfect timing.",
    sentences: [
      "I had to book an elective c-section because baby was breech.",
      "I tried to turn her but nothing worked.",
      "When I went in on the day of the c-section the midwife checked the heartbeat and said I was in labour so it was actually perfect timing",
    ],
  },
  {
    name: "Lara",
    race: "white",
    birthDate: "2021",
    birthAge: "39",
    city: "Johannesburg",
    country: "South Africa",
    countryLivesIn: "South Africa",
    birthKind: "Caeserian",
    noOfChildren: "One",
    noOfChild: "First",
    portrait: "../images/lara-portrait.png",
    birthStory:
      "My labour was planned as baby was breech, so it had to be a c-section (I come from a long line of breech babies including me, my brother, and my mom who was delivered by c-section in the 1950s, so it was not a massive surprise). Before it was confirmed that baby was not going to turn, my gynae said it was up to me how I wanted to deliver (I believe this is common in South African private hospitals) and that there were pros and cons to both caesar and vaginal.'They're both shit', I remember her concluding. I was kind of relieved I wasn't given a choice. I was terrified, labelled as a 'mature' mother in my late 30s after having gone through IVF after not falling pregnant naturally for around six years (possibly due to endometriosis), I was made fully aware of all the possible complications and risks at my age. I was aware that I was lucky to have fallen pregnant, for the first time in my life, with only one viable embryo, and after only one cycle of IVF. The whole process felt like a strange and unbelievable lottery of life. I always describe it as both a horror show and a miracle.Going through the c-section, was admittedly horrible in its own way even though it went relatively well and there were no complications. I could see my husband, who is an anaesthetist, was shaking with nerves. My own anaesthetist was lovely and gentle, as was my gynae who had somehow chosen the most incredible playlist, I loved every song, which calmed me (the only one I can remember is Teenage Dirtbag, which although possibly not pertinent theme wise made me incredibly happy). What was perhaps disturbing about the op was that in the light above I could see a reflection of everything happening below. All I saw was blood and organs, literally coming out of me. Once baby was out, I could hear and see a sense of urgency and rush to reassemble my insides, which is probably not exactly what was happening medically but that is how I perceived it. Everyone sang happy birthday and baby was good, and me and husband cried, and I utilised the morphine pump to address the crazy levels of pain and or discomfort I was feeling. This perhaps made thing a bit fuzzy, although I feel I remember that moment pretty well. Because it was deep COVID lockdown, my husband couldn't stay, and I could have no visitors and I was alone with my baby in our own hospital room, which at the time actually did feel like privilege and a blessing. Apart from those first few hours of just taking each other in, things started to go a bit downhill. From the op you can barely move, can't walk, are reliant on sisters for everything. My biggest issue was feeding. I read various books convincing me that I was going to breast feed no matter what. It was definitely the best way, I had decided. I didn't even research bottle feeding, I had no intention of doing it. It was, to this day, the hardest thing I ever tried to do. Compounded with the pain of the op, the pain of breastfeeding was indescribable, literally blood and pus and bruising.This was with the acknowledgement that I would need help and guidance, employing a lactation consultant who came to see me in the hospital room.",
    sentences: [
      "My labour was planned as baby was breech, so it had to be a c-section (I come from a long line of breech babies including me, my brother, and my mom who was delivered by c-section in the 1950s, so it was not a massive surprise).",
      "Before it was confirmed that baby was not going to turn, my gynae said it was up to me how I wanted to deliver (I believe this is common in South African private hospitals) and that there were pros and cons to both caesar and vaginal.'They're both shit', I remember her concluding. I was kind of relieved I wasn't given a choice.",
      "I was terrified, labelled as a 'mature' mother in my late 30s after having gone through IVF after not falling pregnant naturally for around six years (possibly due to endometriosis), I was made fully aware of all the possible complications and risks at my age.",
      "I was aware that I was lucky to have fallen pregnant, for the first time in my life, with only one viable embryo, and after only one cycle of IVF.",
      "The whole process felt like a strange and unbelievable lottery of life. I always describe it as both a horror show and a miracle.",
      "Going through the c-section, was admittedly horrible in its own way even though it went relatively well and there were no complications.",
      "I could see my husband, who is an anaesthetist, was shaking with nerves. My own anaesthetist was lovely and gentle, as was my gynae who had somehow chosen the most incredible playlist, I loved every song, which calmed me (the only one I can remember is Teenage Dirtbag, which although possibly not pertinent theme wise made me incredibly happy).",
      "What was perhaps disturbing about the op was that in the light above I could see a reflection of everything happening below. All I saw was blood and organs, literally coming out of me.",
      "Once baby was out, I could hear and see a sense of urgency and rush to reassemble my insides, which is probably not exactly what was happening medically but that is how I perceived it.",
      "Everyone sang happy birthday and baby was good, and me and husband cried, and I utilised the morphine pump to address the crazy levels of pain and or discomfort I was feeling.",
      "This perhaps made thing a bit fuzzy, although I feel I remember that moment pretty well.",
      "Because it was deep COVID lockdown, my husband couldn't stay, and I could have no visitors and I was alone with my baby in our own hospital room, which at the time actually did feel like privilege and a blessing.",
      "Apart from those first few hours of just taking each other in, things started to go a bit downhill.",
      "From the op you can barely move, can't walk, are reliant on sisters for everything.",
      "My biggest issue was feeding. I read various books convincing me that I was going to breast feed no matter what. It was definitely the best way, I had decided.",
      "I didn't even research bottle feeding, I had no intention of doing it. Breastfeeding was, to this day, the hardest thing I ever tried to do.",
      "Compounded with the pain of the op, the pain of breastfeeding was indescribable, literally blood and pus and bruising. This was with the acknowledgement that I would need help and guidance, employing a lactation consultant who came to see me in the hospital room.",
    ],
  },
];

export default data;
